import { jwtDecode } from "jwt-decode";

type User = {
  id: number;
  name: string;
  email: string;
  role: string;
};

interface JwtPayload {
  exp?: number;
  iat?: number;
  sub?: string;
}

/**
 * Save authenticated user information.
 *
 * The JWT expiration is controlled by the Spring Boot backend
 * through jwt.expiration.
 */
export function saveAuth(
  token: string,
  user: User
) {
  localStorage.setItem("token", token);
  localStorage.setItem(
    "user",
    JSON.stringify(user)
  );

  // Start timer based on backend JWT expiration
  setupTokenExpiry(token);
}


/**
 * Get JWT token.
 */
export function getToken(): string | null {
  return localStorage.getItem("token");
}


/**
 * Get logged-in user.
 */
export function getUser(): User | null {
  const user = localStorage.getItem("user");

  if (!user) {
    return null;
  }

  try {
    return JSON.parse(user) as User;
  } catch {
    logout();
    return null;
  }
}


/**
 * Check whether the JWT is still valid.
 *
 * The backend controls the expiration through
 * the JWT "exp" claim.
 */
export function isTokenValid(): boolean {
  const token = getToken();

  if (!token) {
    return false;
  }

  try {
    const decoded =
      jwtDecode<JwtPayload>(token);

    if (!decoded.exp) {
      return false;
    }

    return (
      decoded.exp * 1000 > Date.now()
    );
  } catch {
    return false;
  }
}


/**
 * Logout user and remove authentication data.
 */
export function logout() {
  localStorage.removeItem("token");
  localStorage.removeItem("user");
}


/**
 * Setup automatic logout based on the JWT
 * expiration generated by Spring Boot.
 *
 * This does NOT assume 1 hour.
 * It uses the actual "exp" value from the JWT.
 */
export function setupTokenExpiry(
  token?: string
) {
  const currentToken =
    token ?? getToken();

  if (!currentToken) {
    return;
  }

  try {
    const decoded =
      jwtDecode<JwtPayload>(
        currentToken
      );

    if (!decoded.exp) {
      logout();
      return;
    }

    const expirationTime =
      decoded.exp * 1000;

    const remainingTime =
      expirationTime - Date.now();

    // JWT has already expired
    if (remainingTime <= 0) {
      logout();

      window.location.replace(
        "/login"
      );

      return;
    }

    // Logout exactly when backend JWT expires
    window.setTimeout(() => {

      // Make sure the user has not logged
      // in again with a different token.
      if (
        getToken() === currentToken
      ) {
        logout();

        window.location.replace(
          "/login"
        );
      }

    }, remainingTime);

  } catch {
    logout();

    window.location.replace(
      "/login"
    );
  }
}